### ISSUE TITLE
Retrainng with new dataset and generating frozen_inference.pb model file

### ISSUE THREAD

**Issue by NiranjanAntany** [yinguobing/cnn-facial-landmark#57] opened 2019-03-05 13:44 UTC
Hi,

I am working in your eye-lid detection algorithm which uses tensor-flow library. i was stuck in a procedure how to retrain the algorithm with new face and landmark annotated data-set. I have tried with procedure given in tensor-flow and able to get frozen_inference.pb file. but while loading it in your algorithm am getting below error.
---------------------------------------------------------------------------------------------------------
KeyError: "The name 'logits/BiasAdd:0' refers to a Tensor which does not exist. The operation, 'logits/BiasAdd', does not exist in the graph."

-----------------------------------------------------------------------------------------------------
Please help me in the procedure how to retrain with new face data-set and get the frozen_inference,pb file.

Kindly do the needful..

Regards,
Niranjan B

**Comment by vamsichevikala** [comment] 2019-07-02 08:39
@yinguobing Can you share the link for latest code and procedure.

Regards,
Vamsi Chevikala

**Comment by yinguobing** [comment] 2019-07-03 03:25
Duplicate of #53

**Comment by vamsichevikala** [comment] 2019-07-03 06:58
Hi,




         I  downloaded the code from github which you have mentioned, but when I am trying to run landmark.py , it is showing the below  issue.


Error:tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: label/marks (data type: float) is required but could not be found.
     [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_STRING, DT_STRING, DT_FLOAT], _class=["loc:@decode_image/cond_jpeg/cond_png/cond_gif/DecodeGif/Switch_1"], dense_keys=["image/encoded", "image/filename", "label/marks"], dense_shapes=[[], [], [136]], num_sparse=0, sparse_keys=[], sparse_types=[], _device="/device:CPU:0"](arg0, ParseSingleExample/Const, ParseSingleExample/Const, ParseSingleExample/Const_2)]]



Kindly give the solution in detail. Thanks in advance.



Thanks and regards,
Vamsi Chevikala.

________________________________

**Comment by vamsichevikala** [comment] 2019-07-03 07:09
@yinguobing ,    I  downloaded the code from github which you have mentioned, but when I am trying to run landmark.py , it is showing the below  issue.


**_Error:tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: label/marks (data type: float) is required but could not be found.
     [[Node: ParseSingleExample/ParseSingleExample = ParseSingleExample[Tdense=[DT_STRING, DT_STRING, DT_FLOAT], _class=["loc:@decode_image/cond_jpeg/cond_png/cond_gif/DecodeGif/Switch_1"], dense_keys=["image/encoded", "image/filename", "label/marks"], dense_shapes=[[], [], [136]], num_sparse=0, sparse_keys=[], sparse_types=[], _device="/device:CPU:0"](arg0, ParseSingleExample/Const, ParseSingleExample/Const, ParseSingleExample/Const_2)]]_**


Kindly give the solution in detail. Thanks in advance.

Thanks and regards,
Vamsi Chevikala.

**Comment by yinguobing** [comment] 2019-07-03 08:34
@vamsichevikala 
Make sure the feature name is correct, which means the tfrecord file and the example parse function should both have a feature named "label/marks".

Please open a new issue next time if it's not related with the current issue (graph exporting).

**Comment by vamsichevikala** [comment] 2019-07-03 08:47
@Yin Guobing



Thanks. Now I checked  in generate_tfrecord.py, feature named label/marks is not there. Kindly give the solution how to call label/marks in generate_tfrecord.py.


Kindly do the needful.




Regards,

Vamsi Chevikala

________________________________

**Comment by yinguobing** [comment] 2019-07-03 09:14
@vamsichevikala  Please make sure you have the latest code. And again, open new issue if it's not related with the current one.

https://github.com/yinguobing/tfrecord_utility/blob/c5421e26aef66fcb1ee33ea90a15505207176be5/generate_tfrecord.py#L96

**Comment by yinguobing** [comment] 2019-08-07 09:47
The latest commit add functions for exporting model ready to be frozen. Mind the --raw_input argument when exporting saved model.

closing #57

**Closed by yinguobing** 2019-08-07 09:47 UTC
Labels: duplicate

**Comment by abdou31** [comment] 2019-10-24 21:08
Change `labels\marks` to `labels\points` and tell me if this worked.
