### ISSUE TITLE
landmark

### ISSUE THREAD

**Issue by ZlaaM** [yinguobing/cnn-facial-landmark#29] opened 2019-04-24 15:00 UTC
Are you working on updating it ?

**Comment by yinguobing** [comment] 2019-04-26 07:18
I'm trying. :coffee:

**Comment by ZlaaM** [comment] 2019-04-28 07:33
in which version of tensorflow  have you written this code ?

**Comment by yinguobing** [comment] 2019-04-28 07:41
1.4

**Comment by ZlaaM** [comment] 2019-04-28 09:41
please can you share your " frozon_graph.pb " or the name of the output nodes ?
because i still have this problem (
KeyError: "The name 'logits/BiasAdd:0' refers to a Tensor which does not exist. The operation, 'logits/BiasAdd', does not exist in the graph." ) 
thanks alot

**Comment by yinguobing** [comment] 2019-04-28 09:54
May I ask which version of TensorFlow are you using?
It might be Duplicate of #17

**Comment by ZlaaM** [comment] 2019-04-28 10:01
i try tf1.13 , 1.9 and 1.2

**Comment by ZlaaM** [comment] 2019-04-28 10:01
and 1.4

**Comment by ZlaaM** [comment] 2019-04-28 11:05
I tried the same (#17) but the problem still exists

**Comment by ZlaaM** [comment] 2019-04-28 15:35
thank you for your interest .. i solved it

**Comment by yinguobing** [comment] 2019-04-29 03:18
Glad to hear that :smiley: , safe to close #29.

**Closed by yinguobing** 2019-04-29 03:18 UTC
